version: '2'

services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
    - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose:
    - '${MYSQL_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoapp
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  app:
    image: cless91/todo-app:0.0.1-SNAPSHOT
    expose:
    - '${APP_PORT}'
    ports:
    - '${APP_PORT}:${APP_PORT}'
    environment:
      SERVER_PORT: ${APP_PORT}
      LOG_LEVEL: INFO
      JDBC_DRIVER: com.mysql.cj.jdbc.Driver
      DATABASE_USERNAME: mysqluser
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_URL: jdbc:mysql://db:${MYSQL_PORT}/todoapp?createDatabaseIfNotExist=true&serverTimezone=UTC
      HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      DDL_AUTO: create
      BACK_URL: http://localhost:${APP_PORT}

volumes:
  db_data: {}