version: '2'

services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
    - '3306:3306'
    expose:
    - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoapp
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
  app:
    image: todo-app:0.0.1-SNAPSHOT
    expose:
    - '8090'
    ports:
    - '8090:8090'
    environment:
      SERVER_PORT: 8090
      LOG_LEVEL: INFO
      JDBC_DRIVER: com.mysql.cj.jdbc.Driver
      DATABASE_USERNAME: mysqluser
      DATABASE_PASSWORD: mysqlpass
      DATABASE_URL: jdbc:mysql://db:3306/todoapp?createDatabaseIfNotExist=true&serverTimezone=UTC
      HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      DDL_AUTO: create
      BACK_URL: http://localhost:8090

volumes:
  db_data: {}