version: '2'

services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
    - '3306:3306'
    expose:
    - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoapp
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass

volumes:
  db_data: {}