apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todo-app
  name: todo-app
spec:
  ports:
  - port: {{ .Values.application.port }}
    protocol: TCP
    targetPort: {{ .Values.application.port }}
    nodePort: {{ .Values.application.service.port }}
  selector:
    app: todo-app
  type: NodePort
status:
  loadBalancer: {}
