apiVersion: v1
data:
  SERVER_PORT: {{ .Values.application.port | quote }} 
  MYSQL_PORT: {{ .Values.mysql.port | quote }} 
  BACK_URL: {{ .Values.application.backUrl | quote }} 
  DATABASE_URL: jdbc:mysql://mysql:${MYSQL_PORT}/todoapp?createDatabaseIfNotExist=true&serverTimezone=UTC
  DATABASE_USERNAME: mysqluser
  DDL_AUTO: create
  HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
  JDBC_DRIVER: com.mysql.cj.jdbc.Driver
  LOG_LEVEL: INFO
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: todo-app
  namespace: todo-app

