apiVersion: v1
data:
  SERVER_PORT: "8090"
  MYSQL_PORT: "3306"
  BACK_URL: http://cless911c.mylabserver.com:30080
  DATABASE_URL: jdbc:mysql://mysql:${MYSQL_PORT}/todoapp?createDatabaseIfNotExist=true&serverTimezone=UTC
  DATABASE_USERNAME: mysqluser
  DDL_AUTO: create
  HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
  JDBC_DRIVER: com.mysql.cj.jdbc.Driver
  LOG_LEVEL: INFO
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: todo-app
  namespace: todo-app

