apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: todo-app
spec: {}
status: {}

---

apiVersion: v1
data:
  SERVER_PORT: "8090"
  MYSQL_PORT: "3306"
  BACK_URL: http://cless911c.mylabserver.com:30080
  DATABASE_URL: jdbc:mysql://mysql:${MYSQL_PORT}/todoapp?createDatabaseIfNotExist=true&serverTimezone=UTC
  DATABASE_USERNAME: mysqluser
  DDL_AUTO: create
  HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
  JDBC_DRIVER: com.mysql.cj.jdbc.Driver
  LOG_LEVEL: INFO
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: todo-app
  namespace: todo-app

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
  namespace: todo-app
spec:
  containers:
  - image: cless91/todo-app:0.0.1-SNAPSHOT
    name: app
    ports:
    - containerPort: 8090
    resources: {}
    env:
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secrets
          key: mysql-password
    envFrom:
    - configMapRef:
        name: todo-app
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
  namespace: todo-app
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
    nodePort: 30080
  selector:
    run: app
  type: NodePort
status:
  loadBalancer: {}
